language: go

go:
  - "1.11"
  - master

before_install:
  - go get -u golang.org/x/lint/golint

install:
  - go get -d -v ./... && go build -v ./...

script:
  - golint -set_exit_status ./...
  - go test -v ./...

notifications:
  email: false

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
