language: go

go:
  - "1.13"
  - master

before_install:
  - go get -u golang.org/x/lint/golint

install:
  - go get -d -v ./... && go build -v ./...

script:
  - golint -set_exit_status ./...
  - go test -v ./...

notifications:
  email: false
